-- MySQL Script generated by MySQL Workbench
-- Fri Aug 19 00:54:52 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gamerdh
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gamerdh
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gamerdh` DEFAULT CHARACTER SET utf8 ;
USE `gamerdh` ;

-- -----------------------------------------------------
-- Table `gamerdh`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamerdh`.`direccion` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gamerdh`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamerdh`.`genero` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gamerdh`.`plataforma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamerdh`.`plataforma` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gamerdh`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamerdh`.`producto` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `precio` DECIMAL(5,0) NOT NULL,
  `imagen` LONGBLOB NOT NULL,
  `id_genero` INT(11) NOT NULL,
  `id_plataforma` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `genero_idx` (`id_genero` ASC) ,
  INDEX `platafor_idx` (`id_plataforma` ASC) ,
  CONSTRAINT `genero`
    FOREIGN KEY (`id_genero`)
    REFERENCES `gamerdh`.`genero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `platafor`
    FOREIGN KEY (`id_plataforma`)
    REFERENCES `gamerdh`.`plataforma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gamerdh`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamerdh`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `id_direccion` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `dire_idx` (`id_direccion` ASC) ,
  CONSTRAINT `dire`
    FOREIGN KEY (`id_direccion`)
    REFERENCES `gamerdh`.`direccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gamerdh`.`usuario_x_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamerdh`.`usuario_x_producto` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  `id_producto` INT(11) NOT NULL,
  `fecha` DATE NOT NULL,
  `cantidad` DECIMAL(5,0) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_uduario_idx` (`id_usuario` ASC) ,
  INDEX `enlace2_idx` (`id_producto` ASC) ,
  CONSTRAINT `enlace1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `gamerdh`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `enlace2`
    FOREIGN KEY (`id_producto`)
    REFERENCES `gamerdh`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
